trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: wget https://github.com/gohugoio/hugo/releases/download/v0.58.3
    /hugo_0.58.3_Linux-64bit.deb
    -O '$(Pipeline.Workspace)/hugo_0.58.3_Linux-64bit.deb'
  displayName: Download Hugo v0.58.3 Linux x64

- script: sudo dpkg -i $(Pipeline.Workspace)/hugo*.deb
  displayName: Install Hugo

- script: hugo --config "src/config.toml"
  displayName: Build site with Hugo (include future & expired content)