trigger:
- master

pool:
  vmImage: 'win-latest'


steps:
# - checkout: self
#   displayName: 'Checkout repository including submodules'
#   submodules: true
- task: HugoTask@1
  displayName: Build hugo
  inputs:
    source: 'src/'
    destination: '$(Build.ArtifactStagingDirectory)'