baseURL = "https://www.sound-it-out.com"
languageCode = "en-us"
title = "Sound it out"
theme = "meghna-hugo"
publishDir = "../docs/"

summaryLength = 10

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

# Menu
[menu]
    [[menu.nav]]
    name = "What's in it for you?"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Pricing"
    URL = "pricing"
    weight = 3

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 4

# Site params
[params]
home= "Home"
logo = "images/logo.svg"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "Responsive Multipurpose Parallax HTML5 Template"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/hero-area.jpg"
    #icon = "tf-ion-play"
    heading = "Sound it out"
    content= "Why read when you can listen?"
    btn = true
    btnText="Get started"
    btnURL="#pricing"

    # call to action
    #[params.cta]
    #enable = true
    #title = "Sound it out"
    #content = "Why read when you can listen?"
    #btnURL = "#"
    #btnText = "Start a project with us"

    # counter
    [params.counter]
    enable = true
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "Happy users"
        icon = "tf-ion-android-happy"
        count = "0"

        [[params.counter.counterItem]]
        title = "Audio books generated"
        icon = "tf-ion-archive"
        count = "0"

        [[params.counter.counterItem]]
        title = "Positive feedback"
        icon = "tf-ion-thumbsup"
        count = "0"

        [[params.counter.counterItem]]
        title = "Cups of Coffee"
        icon = "tf-ion-coffee"
        count = "2500"

    # footer
    [params.footer]
        copyright = "Sound It Out"
        copyrightURL = "https://www.sound-it-out.com"
        
     [params.contact]
        formEmail = "matthew.hope396@outlook.com"
